name: ecommerce

services:
  cart:
    image: ecommerce-cart:latest
    container_name: ecommerce-cart
    build: ./cart
#    depends_on:
#      - db
    environment:
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=example
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/cart
      - ECOMMERCE_SERVICE_CART
      - SERVER_PORT
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - JWT_SECRET_KEY="=============================secret================================="
#    ports:
#      - "8080:8080"

  postgres:
    image: postgres
    shm_size: 128mb
    volumes:
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
#      - POSTGRES_DB=cart
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
