server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: product-service
        uri: lb://product
        predicates:
        - Path=/api/products/**
        - Method=GET,POST,PUT
